name: add-contributor
run-name: ${{github.event.commits[0].author.username}} has contributed!
on: [push]
jobs:
  adds-contributor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jitterbit/get-changed-files@v1
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install mongodb
      - run: |
         for changed_file in ${{ steps.files.outputs.all }}; do
            echo "Hello"
            npm run add-contributor
         done
        env: 
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          USERNAME: ${{github.event.commits[0].author.username}}
