name: add-contributor
run-name: ${{ github.actor }} has contributed!
on: [push]
jobs:
  adds-contributor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jitterbit/get-changed-files@v1
        with:
          format: 'csv'
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install mongodb
      - run: |
         mapfile -d ',' -t added_modified_files < <(printf '%s,' '${{ steps.files.outputs.added_modified }}')
         for added_modified_file in "${added_modified_files[@]}"; do
            npm run add-contributor
         done
#       - run: npm run add-contributor
        env: 
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          USERNAME: ${{ github.actor }}
          COMMITS: ${{ github.payload }}
