name: add-contributor
run-name: ${{github.event.commits[0].author.username}} has contributed!
on: [push]
jobs:
  adds-contributor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jitterbit/get-changed-files@v1
        with:
          format: 'csv'
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install mongodb
      - run: |
         mapfile -d ',' -t all_files < <(printf '%s,' '${{ steps.files.outputs.all }}')
          for all_file in "${all_files[@]}"; do
            echo "Hello"
            npm run add-contributor --files='${{ steps.files.outputs.all }}'
          done
        env: 
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          USERNAME: ${{github.event.commits[0].author.username}}
          CHANGED_FILES: ${{ steps.files.outputs.all }}
